displayName: mTLS Rules
type: middleware
import: github.com/KizzyCode/mtlsrules-traefik-golang
summary: Middleware to complement mTLS authentication by allowing you to restrict access to a specific subset common names (CN)

testData:
  statusCode: 403
  statusText: mTLS Access Forbidden
